###################################################
################ Quality Assurance ################
###################################################
QA-lint-js:
  stage: tests
  script:
    - cd /srv
    - npm run lint:js

QA-lint-style:
  stage: tests
  script:
    - cd /srv
    - npm run lint:style
